  const config = {
	url: 'baseurl', // modify this setting only if explicit pointing is required.
	mediaBaseUrlFunction:(fileName)=>`http://95.217.181.254/${fileName}.webm`,
	// baseurl: 'http://localhost:8081/api',
	baseurl: 'https://liberate.avniksofttech.com/rest/api',
	imageBaseurl: 'https://liberate.avniksofttech.com/rest/images',
	// imageBaseurl: 'http://localhost:8081/images',
	// stripePublicKey: 'pk_test_BXAJTXJXWiKc7v2qDY35Stzk00GzQ1hnW4',
	stripePublicKey:'pk_test_51K1dQ9LU8HQ73neoaPAfKe94LlUCjXnbCkEWBD28zMFDcqxPdI6hXUvBXuYahKgdiD2pEFV1Q9kQtoIlMxYlxS9J00POGKDtcP',
	contentType: 'application/json',
	accept: 'application/json',
	endpoints: {
		userRegister:'/auth/signup',
		signIn:'/auth/signin',
		userInfo:'/user',
		resetPassword:'/resetpassword',
		changePassword:'/changepass',
		updatePassword:'/updatepass',
		registerSocial:'/auth/socialsignup',
		categories:'/categories',
		services:'/service/all',
		allServiceForUser:'/service/allServicesForUser',
		profileStepOne:'/profile/step1',
		profileStepTwo:'/profile/step2',
		profileStepThree:'/profile/step3',
		ApplyForPractitioner:'/applyforpractitioner',
		ApplyForPractitionerUploadDocs:'/uploadDocs',
		profileImagesUpload:'/uploadUserImages',
		ApplyForPractitionerDeleteDocs:'/delDoc',
		addPractitionerService:'/addPractitionerService',
		serviceList:'/serviceList',
		packagesList:'/packages',
		addPackages:'/addPackage',
		removePackages:'/delPackage',
		dashboardAddServices:'/addPractitionerService',
		editPractitionerService:'/editPractitionerService',
		updatePractitionerService:'/updatePractitionerService',
		userProfile:'/profile',
		interestStep1:'/interest_step1',
		interestStep2:'/interest_step2',
		updateProfile:'/updateProfile',
		createEvent:'/createEvent',
		eventsAll:'/eventsAll',
		languages:'/languages',
		eventDetail:'/eventDeatil',
		getAllPractitioner:'/home',
		favoritePractitioner:'/favourite',
		attachedCard:'/attachCard',
		detachCard:'/detachCard',
		stripCardList:'/stripCardList',
		servicePackageList:'/servicePackageList',
		practitionerServiceList:'/practitionerServiceList',
		eventBooking:'/eventBooking',
		bookings:'/bookings',
		myBookings:'/myBookings',
		userPackages:'/userPackages',
		favoriteUsers:'/favouriteUsers',
		settingData:'/settingData',
		userSetting:'/userSetting',
		addBlockTime:'/addBlockTime',
		unblockTime:'/unblockTime',
		addBankAccount:'/addBankAccount',
		getBankAccounts:'/getBankAccounts',
		verifyBankAccount:'/verifyBankAccount',
		deleteBankAccount:'/deleteBankAccount',
		setDefaultBankAccount:'/setDefaultBankAccount',
		getUserPayments:'/getUserPayments',
		nonRatedEvent:'/nonRatedEvent',
		ratedEvent:'/ratedEvent',
		receivedRating:'/receivedRating',
		submitReview:'/submitReview',
		replyRating:'/replyRating',
		updateProfilePicture:'/updateProfilePicture',
		delUserImage:'/delUserImage',
		notificationsAll:'/notificatoinsAll',
		readNotification:'/readNotification',
		messageList:'/allMsg',
		saveMessage:'/saveMsg',
		stripeConnect:'/stripeConnect',
		stripeApproved:'/stripeApproved',
		allConversation:'/conversations',
		userRecordings:'/userRecordings',
		bookedEventUsers:'/bookedEventUsers',
		userProfileReviews:'/userProfileReviews',
		displayReviewRemove:'/displayReviewRemove',
		displayReview:'/displayReview',
		checkUser:'/checkUser',
		userPackages:'/userPackages',
		emailVerify:'/emailverify',
		adminPracPayment:'/adminPracPayment',
		userPracPayment:'/userPracPayment',
		homeClassEvents:'/homeClassEvents',
		getPaymentDetailForInvoice:'/getPaymentDetailForInvoice'
	}
};
export default config